import type { FormValues } from '@/components/formSchema';

export const defaultValues = {
	property: {
		borough: '',
		block: '',
		lot: '',
		fullAddress: '',
	},
	applicant: {
		applicantName: '',
		applicantDescription: '',
		applicantOther: '',
		isCondoBoardAgent: false,
		boardAuthority: '',
	},
	contact: {
		contactName: '',
		groupNumber: '',
		phone: '',
		mailingAddress: '',
		email: '',
		hasRepresentative: '',
		representativeType: '',
		representativeOther: '',
	},
	valuation: {
		marketValue: undefined,
		sixPercent: undefined,
		assessedValue: undefined,
	},
	hearing: {
		request: '',
	},
	propertyDescription: {
		numKitchens: 0,
		numBaths: 0,
		numBedrooms: 0,
		numOtherRooms: 0,
		numStoriesAboveBasement: 0,
		yearOfConstruction: '',
		parkingIndoor: 0,
		parkingOutdoor: 0,
		lastAlteration: '',
		propertyType: '',
		otherDescription: '',
		residentialUnits: undefined,
		commercialUnits: undefined,
		basement: '',
	},
	nonresidential: {
		wasRented: '',
	},
	saleConstruction: {
		boughtAfter2023: '',
		sellerName: '',
		closingDate: '',
		purchasePrice: undefined,
		signedContractToSell: '',
		buyerName: '',
		contractDate: '',
		contractPrice: undefined,
		offeredForSaleNow: '',
		offeringDetails: '',
		refinancedSince2023: '',
		constructionOrDemolition: '',
		workDescription: '',
		workStartDate: '',
		workCompleteDate: '',
		totalCost: undefined,
	},
	support: {
		attachedProof: false,
		sales: [],
	},
	signature: {
		signerName: '',
		role: '',
		fiduciaryRelationship: '',
		entityName: '',
		corpOfficerTitle: '',
		condoOfficerTitle: '',
		llcSignerTitle: '',
	},
} as unknown as FormValues;
