import type { FormValues } from '@/components/formSchema';

export const defaultValues: FormValues = {
	property: {
		borough: '',
		block: '',
		lot: '',
		fullAddress: '',
	},
	applicant: {
		applicantName: '',
		applicantDescription: 'owner',
		applicantOther: '',
		isCondoBoardAgent: false,
		boardAuthority: '',
	},
	contact: {
		contactName: '',
		groupNumber: '',
		phone: '',
		mailingAddress: '',
		email: '',
		hasRepresentative: 'no',
		representativeType: '',
		representativeOther: '',
	},
	valuation: {
		marketValue: 0,
		sixPercent: 0,
		assessedValue: 0,
	},
	hearing: {
		request: 'paper',
	},
	propertyDescription: {
		numKitchens: 0,
		numBaths: 0,
		numBedrooms: 0,
		numOtherRooms: 0,
		numStoriesAboveBasement: 0,
		yearOfConstruction: '',
		parkingIndoor: 0,
		parkingOutdoor: 0,
		lastAlteration: '',
		propertyType: 'one_family',
		otherDescription: '',
		residentialUnits: 0,
		commercialUnits: 0,
		basement: 'no',
	},
	nonresidential: {
		wasRented: 'no',
	},
	saleConstruction: {
		boughtAfter2023: 'no',
		sellerName: '',
		closingDate: '',
		purchasePrice: 0,
		signedContractToSell: 'no',
		buyerName: '',
		contractDate: '',
		contractPrice: 0,
		offeredForSaleNow: 'no',
		offeringDetails: '',
		refinancedSince2023: 'no',
		constructionOrDemolition: 'no',
		workDescription: '',
		workStartDate: '',
		workCompleteDate: '',
		totalCost: 0,
	},
	support: {
		attachedProof: false,
		sales: [
			{
				saleDate: '',
				salesPrice: undefined,
				address: '',
				blockLot: '',
				totalDwellingUnits: undefined,
			},
			{
				saleDate: '',
				salesPrice: undefined,
				address: '',
				blockLot: '',
				totalDwellingUnits: undefined,
			},
			{
				saleDate: '',
				salesPrice: undefined,
				address: '',
				blockLot: '',
				totalDwellingUnits: undefined,
			},
		],
	},
	signature: {
		signerName: '',
		role: 'individual_applicant',
		fiduciaryRelationship: '',
		entityName: '',
		corpOfficerTitle: '',
		condoOfficerTitle: '',
		llcSignerTitle: '',
	},
};
